### ISSUE TITLE
todo for 0.2.0 release

### ISSUE THREAD

**Issue by TomasTomecek** [TomasTomecek/ansible-bender#11]
* [x] set up a bot to release to github and PyPI
* [x] a changelog 57cf5aa5d31fd0f822f8934e350204b1fd1828b6
* [x] a blog post https://blog.tomecek.net/post/road-to-ansible-bender-0-2-0/
* [x] tinker readme
* [x] figure out caching for file-based actions 5b1a241b0c8573963d30f5fb1ba7ae48839c3136

**Comment by webknjaz** [comment]
You can do publishing with a travis deployment provider like: https://github.com/ansible/ansible-lint/pull/389/files#diff-354f30a63fb0907d4ad57269548329e3R82

P.S. I recommend you using setuptools-scm plugin, which lets you have a Git tag as a single source of version info :)
P.P.S. Please add `__main__.py` to allow `python -m ab`, which makes interpreter selection explicit ;)

**Comment by TomasTomecek** [comment]
I use travis pypi deployment in one of my other projects. The user experience is just terrible, hence within our team we developed a bot on our own: https://github.com/user-cont/release-bot It can release to github, pypi and fedora. Re your first: I'm not sure how that works, the version still needs to be written somewhere, for your other PPS, I'll open an issue, that's a good point (even though I ran ab locally as `python3 ./ansible_bender/cli.py...`.

**Comment by webknjaz** [comment]
> the version still needs to be written somewhere

Just do `git tag -s v1.0.0` and it'll know that on tagged commits the version is `1.0.0`, on subsequent commits it's `1.0.0dev1`,  `1.0.0dev2` etc. Until you tag a new version... It's extremely handly. And when generating sdist and wheel it'll put that version into metadata, of course. So no more two-step process: re-hardcoding of the new version and remembering to have a matching tag, for example.

**Comment by webknjaz** [comment]
As for release process, it'd better integrated with travis this way. Your bot is too workflow-specific and not reusable as a GitHub App. I like to keep all flow in one place/config, so that it's easily discoverable and not split across a bunch of places.

**Comment by TomasTomecek** [comment]
e.g. travis is not able to handle failures during deployments, there are also no deployment hooks (an issue is opened for years to add deployment hooks)

We pretty much write release-bot for ourselves. We tried hard to make it configurable, but you're right: it's very opinionated. On the other hand, I just spent a couple days making the release bot works for this project. I coded a PR to make it act as a github app. Since it runs in openshift just fine, you can easily deploy it to openshift online and use it. I absolutely love when I have control over the software I use - that wasn't the case with travis deployments.

In the end: we should use tools which suits us best :) I give that setup.py plugin a shot and integrate it with the bot maybe. Thanks!

**Comment by webknjaz** [comment]
Cool :) wrt setuptools-scm, feel free to ask me, I'm using it a lot. You don't need a bot integration with it, it plays well with setuptools itself out of the box.

As for the bot, I'll take a look at it, since I was going to implement smth using Deployments API for myself as well + openshift config sounds interesting :)
Here's a few recent GitHub API related projects of mine:
https://github.com/webknjaz/ansiwatch-bot
https://github.com/webknjaz/check-in

As for Travis, they are a small startup, so I can see how they don't have time for everything.. I'm thinking about implementing deployment API triggers for their integration...
